language: node_js
node_js:
- 6
install:
  - npm instal --no-optional
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "a55c8da1c39b"
  - SOURCE_BRANCH: "source"
  - TARGET_BRANCH: "master"
cache:
  directories:
    - node_modules
