[build]
  publish = "public"

[build.environment] 
  ALGOLIA_APP_ID = "YEB4B53LGA"
  ALGOLIA_SEARCH_KEY = "51ca7167d391ff11f246ac45c63e3dc7"
  ALGOLIA_MAIN_INDEX = "netlify_033cc5a8-1836-409b-bcfe-90e50346fa18_master_all"

# TODO Enable
# [[plugins]]
#   package = "@algolia/netlify-plugin-crawler"
#     [plugins.inputs]
#     branches = ['master']

# These redirects will be used by Netlify as well as the client to replace link addresses
# Generic redirects, based on 404 hits
[[redirects]]
  from = "/feed"
  to = "/rss.xml"
[[redirects]]
  from = "/feeds"
  to = "/rss.xml"
[[redirects]]
  from = "/rss"
  to = "/rss.xml"
[[redirects]]
  from = "/assets/etc-thesis.pdf"
  to = "/why-classic"
[[redirects]]
  from = "/sitemapindex.xml"
  to = "/sitemap-index.xml"
[[redirects]]
  from = "/sitemap_index.xml"
  to = "/sitemap-index.xml"
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-index.xml"
# fallback for cloudflare handled redirect
[[redirects]]
  from = "/discord"
  to = "https://discord.com/invite/bMGuZsA"

# 2019 Redirects
[[redirects]]
  from = "/wiki"
  to = "https://github.com/ethereumclassic/wiki/wiki"
[[redirects]]
  from = "/teams"
  to = "/ecosystem/teams"
[[redirects]]
  from = "/roadmap"
  to = "/knowledge/roadmap"
[[redirects]]
  from = "/summit/2019"
  to = "/press/conferences"
[[redirects]]
  from = "/blog/2016-07-11-manifesto"
  to = "/blog/2016-07-11-crypto-decentralist-manifesto"
[[redirects]]
  from = "/blog/2016-07-15-start-project"
  to = "/blog/2016-07-15-start-ethereum-classic-project"
[[redirects]]
  from = "/blog/2016-10-17-hard-fork"
  to = "/blog/2016-10-17-gas-reprice-hard-fork"
[[redirects]]
  from = "/blog/2017-01-17-newsletter"
  to = "/blog/2017-01-17-die-hard-fork-upgrade"

# 2021 Redirects
[[redirects]]
  from = "/development/contribute"
  to = "/development/ecips"
[[redirects]]
  from = "/development/developer-tools"
  to = "/development/tooling"
# moved back below
# [[redirects]]
#   from = "/development/guides"
#   to = "/guides/development"
[[redirects]]
  from = "/development/mining-resources"
  to = "/mining"
[[redirects]]
  from = "/development/network-resources"
  to = "/network"
[[redirects]]
  from = "/development/porting"
  to = "/development"
[[redirects]]
  from = "/ecosystem"
  to = "/services"
[[redirects]]
  from = "/ecosystem/apps-and-protocols"
  to = "/services/apps"
[[redirects]]
  from = "/ecosystem/exchanges"
  to = "/services/exchanges"
[[redirects]]
  from = "/ecosystem/social-channels"
  to = "/community/channels"
[[redirects]]
  from = "/ecosystem/teams"
  to = "/community/teams"
[[redirects]]
  from = "/ecosystem/wallets"
  to = "/services/wallets"
[[redirects]]
  from = "/knowledge/faqs"
  to = "/why-classic"
[[redirects]]
  from = "/knowledge/investor"
  to = "/knowledge/investing"
[[redirects]]
  from = "/knowledge/roadmap"
  to = "/knowledge/history"
[[redirects]]
  from = "/knowledge/what-is-etc"
  to = "/guides/basics"
[[redirects]]
  from = "/press"
  to = "/community/events"
[[redirects]]
  from = "/press/conferences"
  to = "/community/events"
# LODO update this once MEMES section exists
[[redirects]]
  from = "/press/media-kit"
  to = "https://github.com/ethereumclassic/media_kit"
[[redirects]]
  from = "/blog"
  to = "/news/tag/blog"
[[redirects]]
  from = "/news/media"
  to = "/news/tag/news"
# FAQ Restructure
[[redirects]]
  from = "/guides"
  to = "/faqs"
[[redirects]]
  from = "/guides/basics"
  to = "/faqs/users"
[[redirects]]
  from = "/guides/metamask"
  to = "/knowledge/metamask"
[[redirects]]
  from = "/guides/development"
  to = "/development/guides"
